name: panako Docker Build
on:
  push:
    branches:
      - master

jobs:
  docker-package:
    runs-on: ubuntu-latest 
    permissions: write-all
    if: ${{github.ref == 'refs/heads/master'}}
    steps:
    - uses: actions/checkout@v4
    - name: Login to Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker images
      run: |
        docker build resources/scripts/ --build-arg --rm -t ghcr.io/jazzlilo/panako:develop

    - name: Push Docker image to registry
      run: |
        docker push ghcr.io/jazzlilo/panako:develop

